### PR TITLE
feat: add buffer support to append command

### PR DESCRIPTION
**Pull request by tasinet**
Added Buffer support to the append command.

It uses Buffer.concat which was added in node v0.7.11

### CODE REVIEW

**Review by stipsan — APPROVED** [review]
Thanks 😄

**Comment by tasinet** [comment]
Thank you for the immediate response, this is record time for me!

**Comment by stipsan** [comment]
Hehe that's because I started using the native github app https://github.com/mobile and your PR showed up on my watch 😂 👍

**Pull request merged**
