### PR TITLE
feat: Implement psubscribe and punsubscribe

### PR DESCRIPTION
**Pull request by dobesv**
These commands were left for later when the pubsub system was added.  Well, "later" has become "today"!

### CODE REVIEW

**Comment by tomasAlabes** [comment]
Just curious, have you tried this with key space/events?

**Comment by dobesv** [comment]
I don't understand your question, sorry. Is that a package?

**Comment by tomasAlabes** [comment]
Nope, redis feature: https://redis.io/topics/notifications (having enabled them via `notify-keyspace-events KEA`or similar)

```javascript
redis.psubscribe("__key*__:*");
redis.on("pmessage", (pattern, channel, message) => console.log(pattern, channel, message));
```

**Comment by dobesv** [comment]
I haven't done anything with that.


On Jul 23, 2019 at 2:22 PM, Tomas Alabes <notifications@github.com> wrote:

Nope, redis feature: https://redis.io/topics/notifications (having enabled
them via notify-keyspace-events KEAor similar)

redis.psubscribe("__key*__:*");redis.on("pmessage", (pattern, channel,
message) => console.log(pattern, channel, message));

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/stipsan/ioredis-mock/pull/797?email_source=notifications&email_token=AACQBGI4RR7ER4EJQTKK7N3QA5ZBTA5CNFSM4IE66Q72YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD2UPHIA#issuecomment-514388896>,
or mute the thread

**Pull request merged**
