### PR TITLE
fix: add missing zset support for "type" command

### PR DESCRIPTION
**Pull request by sseide**
current implementation of the type command misses the sorted set (zset) type while lots of other commands around sorted sets are implemented. This PR adds the missing code

### CODE REVIEW

**Comment by stipsan** [comment]
Another stuck PR, @sseide could you try pulling in changes from master and push to your branch? Hopefully it'll trigger the testing suite 😅

**Comment by sseide** [comment]
ok - updated and push.

**Comment by sseide** [comment]
The first action - "update compat.md" does not seem to make sense running against oher users pull requests as it is bound to fail. Should it not be excluded while running with foreign git-remotes?

**Comment by stipsan** [comment]
> The first action - "update compat.md" does not seem to make sense running against oher users pull requests as it is bound to fail. Should it not be excluded while running with foreign git-remotes?

You're absolutely right. I haven't had time to refactor that CI script to ignore forks (PR welcome). All I've had time to do is remove it from the list over required checks so PRs can still be merged even though it fails. 😩

**Review by stipsan — APPROVED** [review]

**Comment by sseide** [comment]
not really sure about the github action but i think it would be enough to add a shell script check (maybe as part of "commit changes" step" to compare two of the three `$GITHUB_REPOSITORY`, `$GITHUB_BASE_REF` and/or `git remote -v`.
At least one of it will probably show the other users repository and one your own.

But have not testet - just an idea.

**Comment by sseide** [comment]
And thanks for the merge and release

**Comment by stipsan** [comment]
> not really sure about the github action but i think it would be enough to add a shell script check (maybe as part of "commit changes" step" to compare two of the three `$GITHUB_REPOSITORY`, `$GITHUB_BASE_REF` and/or `git remote -v`. At least one of it will probably show the other users repository and one your own.
> 
> But have not testet - just an idea.

Yep I'm gonna try that https://github.com/stipsan/ioredis-mock/pull/1114

**Pull request merged**
