### PR TITLE
refactor: test for node 6 and upgrade stream-mock to 2.x

### PR DESCRIPTION
**Pull request by b4nst**
Use lodash flatten.

Fixes #727

### CODE REVIEW

**Comment by b4nst** [comment]
Oh cool ! I started to move my repos on Github Action too. Very nice tool to work with IMHO, but sometimes it has weird behavior (beta version behavior 😆).

Regarding v6, pros of Node is that things move fast, cons of Node is that things move fast 😆.

Migrating the entire codebase to TS will be a huge amount of work 😅. I almost entirely redesigned the code architecture for `stream-mock` (and it was a small codebase). But this is a very cool project, and I would be pleased to help. And sometimes reworking from scratch helps make things cleaner 💯

**Comment by stipsan** [comment]
Yeah I have been using it on some private repos for some time now and have seen some weird bugs as well 😂 But it's much easier to create workflows than CircleCi though!

Yep it will indeed, and it'll need to work with `@types/ioredis` I suspect. Any help is greatly appreciated! I do hope we can use the opportunity to clean up a bit indeed 😄

**Comment by b4nst** [comment]
Actually DefinitelyTyped is really well made. When the TS version is ready and deployed, you just have to [mark that your repository bundles its own types](https://github.com/DefinitelyTyped/DefinitelyTyped#removing-a-package) from this version, and that's all. So we don't have to care much about being compatible with `@types/ioredis` (but we could use it as a starting point).

**Comment by stipsan** [comment]
Alright good to know 👍

**Pull request merged**
