### PR TITLE
feat(pubsub): Add shared context among Redis instances

### PR DESCRIPTION
**Pull request by fersilva16**
I'm continuing the #997.

- [x] Create a shared expires instance for context
- [x] Create a shared data instance for context

Closes #997 and #773

### CODE REVIEW

**Review by sibelius — APPROVED** [review]

**Review by stipsan — APPROVED** [review]
This is fantastic! Let's roll it out! 🥳

**Comment by stipsan** [comment]
I'll release this as soon as the tests pass, and change the commit to use `feat` instead of `fix` as I consider this new functionality ☺️

**Comment by stipsan** [comment]
Just did a local checkout to run the test suite, and I'm getting the same failing tests as https://github.com/stipsan/ioredis-mock/runs/4892890568?check_suite_focus=true#step:4:11167

@fersilva16 are you able to run through the test suite?

**Comment by fersilva16** [comment]
> are you able to run through the test suite?

No, my tests are failing too, I'm implemented the shared expires/data and it fixes almost all broken tests, but I'm still working on the rest of the tests, some of them need a refactor.

**Comment by stipsan** [comment]
> > are you able to run through the test suite?
> 
> 
> 
> No, my tests are failing too, I'm implemented the shared expires/data and it fixes almost all broken tests, but I'm still working on the rest of the tests, some of them need a refactor.

Alright, let us know if there's anything we can do to help ☺️

**Comment by fersilva16** [comment]
Now the tests should pass. And should I rebase the commits to one commit only?

**Comment by stipsan** [comment]
> Now the tests should pass. And should I rebase the commits to one commit only?

Awesome! 🥳 Rebase or not is entirely up to you, as all PRs are squash & merged anyways 😌

**Comment by fersilva16** [comment]
I think it's done now! 🥳🎉

**Comment by stipsan** [comment]
> I think it's done now! 🥳🎉

Thank you so much @fersilva16! 🥳 this is fantastic, and I know a lot of people have been waiting for this! (Especially @sibelius) 😄

**Review by stipsan — APPROVED** [review]

**Comment by stipsan** [comment]
The error on the CI seems to be related to an error I saw on an another PR earlier today: https://github.com/stipsan/ioredis-mock/pull/1106#discussion_r789552330

**Comment by fersilva16** [comment]
Fixed!

**Pull request merged**
