### PR TITLE
add mget

### PR DESCRIPTION
**Pull request by stipsan**

### CODE REVIEW

**Comment by stipsan** [comment]
Hey @kesla!

If you plan on adding more features I'd happily add you to the repo 😄

**Comment by kesla** [comment]
Oh! I forgot about this, was some other missing features (ttl / expire) that lead me to not using the mock after all.

But yes! Feel free to add me to the repo and I'll hopefully find time to implement those :)

**Comment by kesla** [comment]
Also, I fixed the linting error

**Comment by stipsan** [comment]
Ah ok, are there any other features than ttl and expire that you needed?
Making issues for them helps signal what is needed the most and makes it easier to prioritize features 😃

**Pull request merged**
