### PR TITLE
Feat: add xadd, xlen, xrange, xrevrange and xread for stream support

### PR DESCRIPTION
**Pull request by critocrito**
Support basic stream operations (https://redis.io/topics/streams-intro) for
the upcoming Redis 5 release. Some features are missing, such as consumer
groups, capped streams or some of the auxiliary commands.

Event ids are auto incremented integers in the form of `1-0`, `2-0`,
etc. Events are stored internally as an array of arrays and for every event an
additional record is kept whether the event has been already polled or not.

```
const redis = new MockRedis({
  mystream: [
    ["1-0", ["key1", "val1", "key2", "val2"]],
    ["2-0", ["key1", "val1", "key2", "val2"]]
  ],
  "stream:mystream:1-0": {polled: false},
  "stream:mystream:2-0": {polled: false},
})
```

To poll events in a blocking manner is supported and the poll happens every
100ms.

```
// This will resolve once a new event becomes available.
redis.xread("BLOCK", "0", "STREAMS", "mystream", "$").then(console.log);
// After 1 second add a new event, that will resolve the waiting `XREAD`
// command.
setTimeout(() => redis.xadd("mystream", "*", "key", "val"), 1000);
```
`ioredis` doesn't support Redis streams yet, but there is [pull request for `redis-commands`](https://github.com/NodeRedis/redis-commands/pull/20) to add support. In the meantime `ioredis`' `createBuiltinCommand` can be used to add support manually:

```
import Redis from "ioredis";

const {string: xadd} = Redis.prototype.createBuiltinCommand("xadd");
const {string: xread} = Redis.prototype.createBuiltinCommand("xread");
Redis.prototype.xadd = xadd;
Redis.prototype.xread = xread;
const redis = new Redis();
```

### CODE REVIEW

**Comment by critocrito** [comment]
Hello @erulabs, I'm not sure I exactly understand where your problem lies. My application has a discrete process that pushes events on a stream, and a discreet process that polls events from a stream. Those processes really operate independently from each other, so yes, they do have separate handles to Redis.

You can use the same handle within the same process if you use asynchronous IO using Promises. I can only point you to examples how to use this code: [the unit tests of `ioredis-mock`](https://github.com/stipsan/ioredis-mock/blob/master/test/commands/xread.js#L80) and here again [some unit tests in some other project that I work on](https://github.com/tracking-exposed/tracking-exposed/blob/master/packages/processor-cli/test/redis.js#L32).

**Comment by erulabs** [comment]
Just that the example code above of:
```
// This will resolve once a new event becomes available.
redis.xread("BLOCK", "0", "STREAMS", "mystream", "$").then(console.log);
// After 1 second add a new event, that will resolve the waiting `XREAD`
// command.
setTimeout(() => redis.xadd("mystream", "*", "key", "val"), 1000);
```
will not work against a real, running redis 5 service, since the `xadd` will never be executed, as the `xread` is blocking _the redis connection_. It doesn't block the node.js thread, so the `xadd` javascript function is called, but the real redis server would not get that call, and thus the `xread` promise would not resolve. If, from another process, you executed an xadd, _then_ the xread would resolve.

I can provide some example code if you want (or maybe a container so its easy to replicate against a running redis service), but just wanted to point out that the example and the mock test test would not work in the real world.

**Comment by critocrito** [comment]
Ahh I see. Yeah, the above code snippet relates to a unit test using `ioredis-mock`. I have never tried the exact same code on a *real* redis client. Thanks for pointing it out. My real world use case doesn't push and pull to the same stream within the same process or on the same client handle.

**Comment by erulabs** [comment]
No problem - thanks for the library! Worth noting that I brought this up on the redis mailing lists and Antirez himself came to the rescue, and we now have a "CLIENT UNBLOCK" syntax (here is the discussion: https://groups.google.com/forum/#!topic/redis-db/bfgZ-3QgCmM)!

**Comment by stipsan** [comment]
Thanks for the detailed info @erulabs and @critocrito! 

I would love for this to behave more accurately. The whole point of this library is to be as accurate in its emulation as possible. Right now there is no emulation of things like network connectivity, sentinels or pub/sub. I'll make an issue linking to the information above to ensure it'll be handled correctly in the future.

**Pull request merged**
