### PR TITLE
fix(commands): implement correct redis pattern matching algorithm instead of using minimatch

### LINKED ISSUE #1058: keys glob matching doesn't follow redis spec
Redis uses a glob-like syntax for KEYS, but not all glob patterns are supported:

> Supported glob-style patterns:
> - h?llo matches hello, hallo and hxllo
> - h*llo matches hllo and heeeello
> - h[ae]llo matches hello and hallo, but not hillo
> - h[^e]llo matches hallo, hbllo, ... but not hello
> - h[a-b]llo matches hallo and hbllo
> 
> https://redis.io/commands/keys

The KEYS implementation here is [just using `minimatch`](https://github.com/stipsan/ioredis-mock/blob/master/src/commands/keys.js#L4), which implements more patterns of the glob spec, and also has some filename specific behaviour. One example where this breaks is when `key = /some/key/` and `pattern = /some*/`. Redis will match this while the mock won't.

> mset /some/key/ value
> OK
> KEYS /some*
> 1) "/some/key/"

--

> minimatch('/some/key/', '/some*')
> false

### LINKED ISSUE #1075: psubscribe wildcards don't work correctly
The mock implementation uses `minimatch`, which is not a valid choice because it differs from redis psubscribe pattern behavior in numerous ways.

As a simple example, `*` should match any redis channel, but `minimatch('a/b', '*') === false`.

A little bit of code review on the psubscribe PR should have caught the three issues I've filed so far.

### PR DESCRIPTION
**Pull request by jedwards1211**
fix #1075
fix #1058 

I just looked up redis' own code for doing the pattern match and translated it to JS and added tests.

### CODE REVIEW

**Review by stipsan — COMMENTED** [review]
Delete [this file](https://github.com/stipsan/ioredis-mock/blob/5e8ebed9bc481475bf70e4770f8890fe16db585b/ioredis-mock-5.5.5.tgz) and I'll approve, merge, and release 😄 
Stellar work! 👍

**Comment by jedwards1211** [comment]
Is there something I need to do to fix this error in CI?

```
remote: Permission to jedwards1211/ioredis-mock.git denied to github-actions[bot].
fatal: unable to access 'https://github.com/jedwards1211/ioredis-mock.git/': The requested URL returned error: 403
```
I don't understand why GitHub would forbid access to my fork...

**Comment by jedwards1211** [comment]
Okay nevermind, I see it's trying to regenerate `compat.md` and push it.  Nice automation!  I'm amazed how few projects take advantage of `semantic-release`.

**Pull request merged**
