### PR TITLE
Dpikt/buffer args

### PR DESCRIPTION
**Pull request by dpikt**
Prevent conversion of string buffer arguments to strings

### CODE REVIEW

**Comment by dpikt** [comment]
@stipsan any idea why appveyor failed? :(

**Comment by stipsan** [comment]
Appveyor is failing to install yarn, I'm not sure why it fails but it's clear that it's nothing to do with your PR.
I think it's safe to assume that the changes in this PR will not behave differently on windows compared to other platforms so I'm gonna merge this one 👍

**Comment by stipsan** [comment]
I'll update the change log and prepare a release tomorrow 😊

**Comment by dpikt** [comment]
@stipsan awesome, thanks!

**Pull request merged**
