### PR TITLE
feat: support LIMIT in zrangebyscore (#918)

### PR DESCRIPTION
**Pull request by mishan**

### CODE REVIEW

**Comment by mishan** [comment]
@stipsan The build failure doesn't appear to be related to my changes. One of them is complaining about nodejs version, another is trying to push something to my fork of your repo (which I made so I can make this PR :) )

**Comment by barakharizima** [comment]
@mishan just reminding that if you get the chance to add the same support on the following commands: `zrevrangebyscore`, `zrevrangebylex`, `zrangebylex` which support LIMIT option as well, that would be awesome!

**Comment by mishan** [comment]
@barakharizima done

**Pull request merged**
