### PR TITLE
feat: Added Typescript definition file.

### PR DESCRIPTION
**Pull request by notaphplover**
Added Typescript definition file.
Updated package.json in order to notify Typescript where the types of the module are.

### CODE REVIEW

**Comment by stipsan** [comment]
I saw one project that started doing it this way: https://github.com/testing-library/react-testing-library/blob/89d11b08c61f3cf5af770c61a03d564b3fdc301c/package.json#L50

**Comment by notaphplover** [comment]
> Since library definitions that get out of sync can be very painful I think we should consider publishing it on DefinitelyTyped instead of maintaining it on here.
> We can then add a `@types/ioredis-mock` dependency here so that for TS users you get somewhat the same experience, but fixes to the definitions can be done faster, and if something is wrong it's easier to ignore the `@types/ioredis-mock` definitions and just fallback to any. What do you think? 😄

I think it's the best approach, let's do it 😃

**Comment by jogelin** [comment]
any news on this PR or @types library ?

**Comment by notaphplover** [comment]
> any news on this PR or @types library ?

Sry guys, I've been so busy :(, I'll do it this weekend

**Comment by notaphplover** [comment]
@jogelin Thank you for the reminder, I really forgot this PR

**Comment by squareloop1** [comment]
Is there any update on this PR or types for this in DefinitelyTyped?

**Comment by stipsan** [comment]
Hi @squareloop1, not really. We'll most likely rewrite this repo to be written in TS and generate the type defs during build. I don't have any timeframe for that though.

**Comment by Hongbo-Miao** [comment]
(Add some info, just found https://www.npmjs.com/package/@types/ioredis-mock which works well for me 😃)

**Comment by stipsan** [comment]
Use https://www.npmjs.com/package/@types/ioredis-mock for now

**Pull request closed without merging**
