### PR TITLE
fix(pubsub): try to share same config data among redis instances, fix…

### PR DESCRIPTION
**Pull request by sibelius**
… #773

I don't think this is the best way to implement this

### CODE REVIEW

**Comment by sibelius** [comment]
we probably need a way to clear the map after use, not sure when is the best time for this

**Comment by stipsan** [comment]
For starters whenever `flushall` or `flushdb` is called, that's the right time to clear the data in the map. In fact `ioredis` itself is calling `FLUSH ALL` between each test in its own integration suite: https://github.com/luin/ioredis#running-tests

It's a bit tricky to define `after use`. The goal is after all to be as aligned to the real world behavior of ioredis and redis as possible. I'm not sure we can clear the map automatically without breaking that contract.

**Comment by stipsan** [comment]
If you make these changes you'll be able to control the cleanup logic between tests:

`A tests/hooks.js`:
```
/* eslint-disable no-unused-vars */
import * as MockRedis from '../src';

export const mochaHooks = {
  afterEach(done) {
    // @TODO just a temporary workaround
    MockRedis.RedisContextMap.clear();

    // onst redis = new MockRedis();
    // redis.flushall().finally(() => done());
  },
};
```
`M package.json`:
```diff
-"test": "nyc mocha --require @babel/register --recursive",
+"test": "nyc mocha --require @babel/register --require test/hooks --recursive",
```
`M src/index.js`:
```diff
-const RedisContextMap = new Map();
+export const RedisContextMap = new Map();
```

**Comment by sibelius** [comment]
`flushall` wouldn't be enough?

**Comment by stipsan** [comment]
it should be enough, however, I ran into a lot of errors in the testing suite.
It's unclear exactly what the cause is, so I added the export of `RedisContextMap` as a temporary fix while going over the tests to find out why they're failing.

**Comment by jgcmarins** [comment]
what is missing from this one to be merged?

**Pull request closed without merging**
