### PR TITLE
feat: #1154 getBuffer matching ioredis

### LINKED ISSUE #1154: getBuffer() does not match the behavior of ioredis
Consider the following example:
 
```javascript
const Redis = require('ioredis-mock')
const redis = new Redis()
const value = Buffer.from('1T+HJWDNyTa4jJXwoBbV6Q==', 'base64')
await redis.set('foo', value)
const returnedValue = await redis.getBuffer('foo')
assert.equal(value.toString('base64'), returnedValue.toString('base64'))
```

Result:
```javascript
Uncaught:
AssertionError [ERR_ASSERTION]: '1T+HJWDNyTa4jJXwoBbV6Q==' == '77+9P++/vSVg77+977+9Nu+/ve+/ve+/ve+/vRbvv73vv70='
    at REPL37:1:8
    at Script.runInThisContext (vm.js:134:12)
    at REPLServer.defaultEval (repl.js:566:29)
    at bound (domain.js:421:15)
    at REPLServer.runBound [as eval] (domain.js:432:12)
    at REPLServer.onLine (repl.js:909:10)
    at REPLServer.emit (events.js:412:35)
    at REPLServer.emit (domain.js:475:12)
    at REPLServer.Interface._onLine (readline.js:434:10)
    at REPLServer.Interface._line (readline.js:791:8) {
  generatedMessage: true,
  code: 'ERR_ASSERTION',
  actual: '1T+HJWDNyTa4jJXwoBbV6Q==',
  expected: '77+9P++/vSVg77+977+9Nu+/ve+/ve+/ve+/vRbvv73vv70=',
  operator: '=='
}
```

What's going on here? Well, it looks like the [implementation for `get`](https://github.com/stipsan/ioredis-mock/blob/v7.0.1/src/commands/get.js#L1-L9) always calls `Buffer.toString()` on values that were originally stored as buffers. This encodes the data returned as utf8, which breaks on bytes that don't have representation in unicode. From the [node Buffer docs](https://nodejs.org/api/buffer.html#buffer_buffer):
> When decoding a Buffer into a string that does not exclusively contain valid UTF-8 data, the Unicode replacement character U+FFFD � will be used to represent those errors.

To bring this into compliance with ioredis, we likely need to change the `getBuffer` implementation to detect that a key was stored as a buffer and return it as such without interpretation. I think this will yield the same behavior as ioredis `get` and `getBuffer`.

Will send PR.

### PR DESCRIPTION
**Pull request by ryanwitt**
fixes #1154

### CODE REVIEW

**Comment by ryanwitt** [comment]
Just realizing there are a bunch of other places to check besides getBuffer, here. 😅

**Comment by ryanwitt** [comment]
```sh
$ git grep ".toString()" -- src
src/command.js:  return arg instanceof Buffer ? arg : arg.toString()
src/commands/decr.js:  this.data.set(key, nextVal.toString())
src/commands/decrby.js:  this.data.set(key, nextVal.toString())
src/commands/defineCommand.js:      interop.push(vm.L, ['error', err.toString()])
src/commands/get.js:    return value.toString()
src/commands/hincrby.js:  hash[field] = nextVal.toString()
src/commands/hincrbyfloat.js:  hash[field] = (curVal + parseFloat(increment)).toString()
src/commands/incr.js:  this.data.set(key, nextVal.toString())
src/commands/incrby.js:  this.data.set(key, nextVal.toString())
src/commands/incrbyfloat.js:  this.data.set(key, (curVal + parseFloat(increment)).toString())
src/commands/object.js:    if ([...val].every(n => n === parseInt(n, 10).toString())) {
src/commands/object.js:    if (val === parseInt(val, 10).toString()) {
src/commands/zincrby.js:  return score.toString()
src/commands/zscan.js:    zKeys.push([value, score.toString()])
src/commands/zscore.js:  return entry.score.toString()
```

Seems like `get.js` was the only place where this was happening in a bad way.

**Review by stipsan — APPROVED** [review]
LGTM, thanks @ryanwitt! 🥳

**Pull request merged**
