### PR TITLE
test(lua): #arr is off-by-one because arrays are 1-based

### PR DESCRIPTION
**Pull request by Skn0tt**
Hi there! I observed a bug where `#arr` returns the wrong array length. This PR contains a reproduction test.
I haven't yet found a way to fix this easily - any ideas from the maintainers?

cc https://github.com/quirrel-dev/quirrel/issues/452

### CODE REVIEW

**Comment by Skn0tt** [comment]
Dug a little deeper. I was able to fix the repro (and not break any other tests) by subtracting 1 here:

https://github.com/fengari-lua/fengari-interop/blob/1626687fb15452cdd82ee522955dd1f144ea7a68/src/js.js#L847

**Comment by Skn0tt** [comment]
4037850 fixed it! fengari-interop allows [injection of a custom length function](https://github.com/fengari-lua/fengari-interop/blob/1626687fb15452cdd82ee522955dd1f144ea7a68/src/js.js#L845), which does the trick.

**Comment by Skn0tt** [comment]
@stipsan bumping in case this PR got lost.

**Comment by stipsan** [comment]
Thanks @Skn0tt !! This summer and fall has been super busy on my end so it's taken a while for me to catch up on everything on my FOSS 😄

**Pull request merged**
